# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C87z-mbSUMlL582OB7gMVRuHsWOKazUK
"""

import streamlit as st
import pandas as pd
from datetime import datetime

# ====================== КОНФИГУРАЦИЯ ======================
st.set_page_config(
    page_title="RUZ Commission Planner",
    page_icon="📅",
    layout="wide"
)

st.title("📅 RUZ Commission Planner")
st.markdown("**Планирование комиссий и поиск свободных окон в расписании СПбГТУ**")

# Боковая панель
with st.sidebar:
    st.header("Настройки")
    st.info("Приложение работает на Supabase PostgreSQL")

    if st.button("🔄 Полностью обновить расписание", type="primary"):
        st.warning("Парсер будет добавлен на следующем этапе")
        # Здесь позже будет вызов парсера

# Основные вкладки
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Обновление данных",
    "Поиск свободных окон",
    "Планирование комиссий",
    "Статистика нагрузки",
    "Сохранённые варианты"
])

with tab1:
    st.subheader("Обновление расписания")
    col1, col2 = st.columns(2)
    with col1:
        start_date = st.date_input("Дата начала", datetime(2026, 2, 1))
    with col2:
        end_date = st.date_input("Дата окончания", datetime(2026, 5, 25))

    st.info("Кнопка полного обновления будет работать после подключения парсера и Supabase.")

with tab2:
    st.subheader("Поиск свободных окон")
    st.info("Фильтры и поиск будут добавлены на следующих этапах.")

with tab3:
    st.subheader("Планирование комиссий")
    st.info("Выбор преподавателей, правила состава — на следующих этапах.")

with tab4:
    st.subheader("Статистика нагрузки")
    st.info("Здесь будет отображаться нагрузка по дисциплинам и преподавателям.")

with tab5:
    st.subheader("Сохранённые варианты комиссий")
    st.info("Список сохранённых вариантов появится позже.")

st.caption("Приватное приложение • Данные хранятся в Supabase")